// tailwind.config.js
// [ ! ] 這是修復後的 V1.0 最終版本

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './content/**/*.{json,md}',
  ],
  theme: {
    fontFamily: {
      sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'sans-serif'],
    },
    extend: {
      colors: {
        primary: '#4A6C56',
        sage: '#4A6C56',
        paper: '#FFFFFF',
        background: '#F5F5F7',
        foreground: '#1D1D1F',
        ink: '#1D1D1F',
        inkSoft: '#4B4B4F',
        line: '#E6E6EA',
        border: '#E6E6EA',
        card: '#FFFFFF',
        'card-foreground': '#1D1D1F',
        muted: '#4B4B4F',
        'muted-foreground': '#4B4B4F',
        accent: '#0070C9',
        sustain: {
          primary: '#4A6C56',
          primarySoft: '#6B8872',
          accent: '#0070C9',
          pageBg: '#F5F5F7',
          cardBg: '#FFFFFF',
          cardBorder: '#E2E4EA',
          'cardBorder-dark': '#374151',
          textMain: '#1D1D1F',
          textMuted: '#4B5563',
          navBg: '#FFFFFF',
          navBorder: '#E5E7EB',
          navText: '#1D1D1F',
          navTextMuted: '#6B7280',
          link: '#4A6C56',
          linkHover: '#365040',
          green: '#4A6C56',
          greenDark: '#3A5443',
          bg: '#F5F5F7',
          'bg-dark': '#050816',
          text: '#1D1D1F',
          'text-dark': '#E5E7EB',
          surface: '#FFFFFF',
          'surface-dark': '#111827',
          'surface-muted': '#F9FAFB',
          'surface-muted-dark': '#1F2937',
          'surface-elevated': '#FDFDFE',
          'surface-elevated-dark': '#1F2937',
        },
        brand: {
          bg: '#F6F2EA',
          primary: '#C7A87A',
          primaryDark: '#B18F5F',
          sage: '#4A6C56',
          ink: '#1F2933',
        },
      },
      boxShadow: {
        card: '0 20px 55px rgba(15, 23, 42, 0.08)',
        soft: '0 2px 10px rgba(0,0,0,0.06)',
        ssgCard: '0 18px 50px rgba(15, 23, 42, 0.08)',
        sustainCard: '0 12px 40px rgba(15, 23, 42, 0.08)',
        legacyCard: '0 8px 24px rgba(0,0,0,0.08)',
      },
      borderRadius: {
        xl: '1rem',
        '2xl': '1.25rem',
        '3xl': '2rem',
        '4xl': '2.5rem',
        ssgCard: '16px',
        ssgButton: '9999px',
        card: '1rem',
        pill: '999px',
      },
      maxWidth: {
        wrap: '1200px',
        page: '72rem',
        'screen-content': '100rem',
      },
      spacing: {
        section: '5rem',
        'section-y': '3.75rem',
        'section-y-sm': '2.5rem',
      },
    },
  },
  // [ ! ] 確保 plugins 陣列看起來像這樣
  plugins: [
    require('@tailwindcss/typography'),
  ],
};
