const redirect = (source, destination) => ({ source, destination, permanent: true });

const redirectMap = [
  redirect('/service', '/coaching'),
  redirect('/services', '/coaching'),
  redirect('/services/transition', '/coaching'),
  redirect('/services/transition-coaching', '/coaching'),
  redirect('/services/reset-sprint', '/coaching'),
  redirect('/services/deepening-practice', '/coaching'),
  redirect('/services/early-career', '/coaching'),
  redirect('/services/early-career-coaching', '/coaching'),
  redirect('/services/graduates', '/coaching'),
  redirect('/services/for-young-professionals', '/coaching'),
  redirect('/services/career-return/:path*', '/coaching?focus=returning-to-work'),
  redirect('/services/returner-coaching', '/coaching?focus=returning-to-work'),
  redirect('/services/for-career-returners', '/coaching?focus=returning-to-work'),
  redirect('/services/for-parents-returning', '/coaching?focus=returning-to-work'),
  redirect('/services/working-parents', '/coaching?focus=returning-to-work'),
  redirect('/for/mid-career-returners', '/coaching?focus=returning-to-work'),
  redirect('/for/parents-returning-to-work', '/coaching?focus=returning-to-work'),
  redirect('/services/immigrant-job/:path*', '/coaching?focus=new-to-uk'),
  redirect('/services/newcomers-uk', '/coaching?focus=new-to-uk'),
  redirect('/services/uk-newcomer-coaching', '/coaching?focus=new-to-uk'),
  redirect('/services/for-newcomers-to-uk', '/coaching?focus=new-to-uk'),
  redirect('/for/newcomers-to-uk', '/coaching?focus=new-to-uk'),
  redirect('/services/leadership', '/coaching?focus=leadership-transition'),
  redirect('/services/mid-career', '/coaching?focus=career-change'),
  redirect('/services/mid-career-coaching', '/coaching?focus=career-change'),
  redirect('/services/graduate-start/:path*', '/coaching'),
  redirect('/services/:path*', '/coaching'),
  redirect('/about/team/:path*', '/about'),
  redirect('/about/coach', '/about'),
  redirect('/about/story', '/about'),
  redirect('/about/values', '/about'),
  redirect('/about/approach/:path*', '/about'),
  redirect('/about/ethics/:path*', '/about'),
  redirect('/team/:path*', '/about'),
  redirect('/resources', '/reflection-tools'),
  redirect('/blog/:path*', '/reflection-tools'),
  redirect('/faq', '/coaching#faq'),
  redirect('/corporate/:path*', '/coaching'),
  redirect('/tools/behaviour-experiment-ladder', '/tools/behaviour-ladder'),
  redirect('/tools/behaviour-experiment-ladder.html', '/tools/behaviour-ladder'),
  redirect('/tools/choice-clarifier.html', '/tools/choice-clarifier'),
  redirect('/tools/emotion-triangle.html', '/tools/emotion-triangle'),
  redirect('/tools/role-separation.html', '/tools/role-separation'),
  redirect('/tools/self-talk-reframe.html', '/tools/self-talk-reframe'),
  redirect('/tools/thought-log.html', '/tools/thought-log'),
  redirect('/tools/values-map.html', '/tools/values-map'),
  redirect('/tools/emotion-triangle-ai', '/reflection-tools'),
  redirect('/tools/emotion-triangle-ai.html', '/reflection-tools'),
  redirect('/en/:path*', '/:path*'),
  redirect('/en-US/:path*', '/:path*'),
];

module.exports = { redirectMap };
