import type { FormEvent } from 'react';
import { useState } from 'react';
import type { GetStaticProps } from 'next';
import Link from 'next/link';
import { EnvelopeSimple, ShieldCheck } from '@phosphor-icons/react';
import MainLayout from '@/components/layout/MainLayout';
import { PageHero } from '@/components/site/ContentPage';
import { CONTACT_EMAIL, normaliseLocale } from '@/content/siteStrategy';

const initialForm={name:'',email:'',language:'English',role:'',organisation:'',useful:'',privacy:false};
export default function Contact({locale}:{locale:string}){
  const zh=locale==='zh-TW';const[form,setForm]=useState(initialForm);const[status,setStatus]=useState<'idle'|'sending'|'sent'|'error'>('idle');const[message,setMessage]=useState('');
  const update=(event)=>{const target=event.target;setForm(current=>({...current,[target.name]:target.type==='checkbox'?target.checked:target.value}))};
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setStatus('sending');setMessage('');try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to send');setStatus('sent');setMessage(zh?'謝謝你把情境寫下來。Hao-Cheng 會親自閱讀並以電子郵件回覆。':'Thank you for writing about the situation. Hao-Cheng will read it personally and reply by email.');setForm(initialForm)}catch(error){setStatus('error');setMessage(zh?`目前無法送出。請直接來信至 ${CONTACT_EMAIL}。`:`The form could not be sent. Please email ${CONTACT_EMAIL} directly.`)}}
  const label='block text-sm font-semibold text-[#173d2f]';const field='mt-2 w-full border border-[#173d2f]/20 bg-[#fbfaf6] px-4 py-3 text-base text-[#10251d] transition focus:border-[#27634e] focus:outline-none focus:ring-2 focus:ring-[#27634e]/15';
  return <>
    <PageHero image="/images/hero-v2/contact.webp" imageAlt={zh?'一位專業人士寫下尚未整理完整的情境':'A professional writing down a situation that is not yet fully resolved'} eyebrow={zh?'寫給 HAO-CHENG':'WRITE TO HAO-CHENG'} title={zh?'不必先把事情整理完整':'You do not need to make the situation sound tidy'} intro={zh?'先寫下你正在承擔什麼、兩邊向你要求什麼，以及目前最難處理的那一部分。每一則訊息都由 Hao-Cheng 本人閱讀。':'Write about what you are carrying, what both sides are asking of you and the part that feels hardest to handle. Every message is read personally by Hao-Cheng.'} meta={zh?'沒有預約連結，也不需要先同意開始 Coaching。':'No booking link and no requirement to commit to coaching.'} />
    <section className="bg-[#fbfaf6]"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-12 lg:py-28">
      <form onSubmit={submit} className="lg:col-span-7"><div className="grid gap-7">
        <div className="grid gap-7 sm:grid-cols-2"><div><label className={label} htmlFor="name">{zh?'姓名':'Name'}</label><input className={field} id="name" name="name" autoComplete="name" required minLength={2} value={form.name} onChange={update}/></div><div><label className={label} htmlFor="email">{zh?'電子郵件':'Email'}</label><input className={field} id="email" name="email" type="email" autoComplete="email" required value={form.email} onChange={update}/></div></div>
        <div><label className={label} htmlFor="language">{zh?'希望使用的語言':'Preferred language'}</label><select className={field} id="language" name="language" required value={form.language} onChange={update}><option>English</option><option>繁體中文</option></select></div>
        <div><label className={label} htmlFor="useful">{zh?'你現在正在承擔什麼？':'What are you carrying right now?'}</label><p className="mt-2 text-sm leading-6 text-[#62736c]">{zh?'不需要寫成正式摘要。角色、兩邊的期待，以及現在最難處理的事情就足夠。請不要提供醫療、證件或財務資料。':'This does not need to be a formal summary. Your role, expectations on both sides and what feels hardest are enough. Do not include medical, identity or financial records.'}</p><textarea className={`${field} min-h-52 resize-y`} id="useful" name="useful" required minLength={30} maxLength={3000} value={form.useful} onChange={update}/></div>
        <details className="border-y border-[#173d2f]/15 py-5"><summary className="cursor-pointer font-semibold text-[#27634e]">{zh?'選填：角色與組織資料':'Optional: role and organisation details'}</summary><div className="mt-6 grid gap-7 sm:grid-cols-2"><div><label className={label} htmlFor="role">{zh?'你的角色':'Your role'}</label><input className={field} id="role" name="role" maxLength={120} value={form.role} onChange={update}/></div><div><label className={label} htmlFor="organisation">{zh?'公司或組織':'Company or organisation'}</label><input className={field} id="organisation" name="organisation" autoComplete="organization" maxLength={160} value={form.organisation} onChange={update}/></div></div></details>
        <label className="flex items-start gap-3 text-sm leading-6 text-[#53675f]"><input className="mt-1 h-4 w-4" type="checkbox" name="privacy" required checked={form.privacy} onChange={update}/><span>{zh?'我已閱讀隱私政策，並同意 SustainSage 使用這些資料回覆我的訊息。':'I have read the privacy policy and agree that SustainSage may use this information to respond.'} <Link className="font-semibold text-[#27634e] underline" href="/legal/privacy">{zh?'隱私政策':'Privacy Policy'}</Link></span></label>
        <button className="ssg-primary-button justify-center disabled:cursor-wait disabled:opacity-60 sm:justify-self-start" disabled={status==='sending'} type="submit">{status==='sending'?(zh?'傳送中…':'Sending…'):(zh?'把情境寫給 Hao-Cheng':'Send the situation to Hao-Cheng')}</button>
        <div aria-live="polite">{message?<p className={`border-l-2 p-4 text-sm ${status==='sent'?'border-emerald-700 bg-emerald-50 text-emerald-950':'border-amber-700 bg-amber-50 text-amber-950'}`}>{message}</p>:null}</div>
      </div></form>
      <aside className="self-start border-l-2 border-[#d9b27c] pl-7 lg:col-span-4 lg:col-start-9"><EnvelopeSimple className="h-7 w-7 text-[#27634e]"/><h2 className="mt-6 text-2xl font-medium text-[#173d2f]">{zh?'也可以直接來信':'Email directly instead'}</h2><a href={`mailto:${CONTACT_EMAIL}`} className="mt-4 block break-all font-semibold text-[#27634e] underline underline-offset-4">{CONTACT_EMAIL}</a><p className="mt-6 leading-7 text-[#53675f]">{zh?'如果議題不適合 Coaching，Hao-Cheng 會直接說明，不會要求你先參加銷售通話。':'If coaching is not suitable, Hao-Cheng will say so directly. You will not be asked to attend a sales call first.'}</p><div className="mt-7 flex gap-3 border-t border-[#173d2f]/10 pt-6 text-sm leading-6 text-[#53675f]"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-[#27634e]"/><p>{zh?'表單經加密連線傳送。請只提供判斷是否適合回覆所需的資訊。':'The form is sent over an encrypted connection. Share only what is needed to understand whether a response is appropriate.'}</p></div></aside>
    </div></section>
  </>;
}
Contact.getLayout=(page)=><MainLayout seo={{title:page.props.locale==='zh-TW'?'把情境寫給 Hao-Cheng':'Write to Hao-Cheng about the situation',description:page.props.locale==='zh-TW'?'向 Hao-Cheng 說明你正在承擔的跨境領導情境。':'Tell Hao-Cheng about the cross-border leadership situation you are carrying.'}}>{page}</MainLayout>;
export const getStaticProps:GetStaticProps=async({locale})=>({props:{locale:normaliseLocale(locale)}});
